"""documents generes : fiche de cours et provenance

Revision ID: e7be031d7242
Revises: ba8c73e2364f
Create Date: 2026-10-02 07:38:25.104439

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e7be031d7242"
down_revision: str | Sequence[str] | None = "ba8c73e2364f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "generated_document",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("teacher_id", sa.Integer(), nullable=False),
        sa.Column("teaching_unit_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("provider_name", sa.String(length=40), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("validated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["teacher_id"],
            ["teacher.id"],
        ),
        sa.ForeignKeyConstraint(
            ["teaching_unit_id"],
            ["teaching_unit.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "generated_field",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("generated_document_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("field", sa.String(length=60), nullable=False),
        sa.Column("value", sa.Text(), nullable=True),
        sa.Column("provenance", sa.String(length=30), nullable=False),
        sa.Column("source_ref", sa.String(length=400), nullable=True),
        sa.Column("edited_by_teacher", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["generated_document_id"],
            ["generated_document.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("generated_document_id", "field"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("generated_field")
    op.drop_table("generated_document")
    # ### end Alembic commands ###
